### ISSUE TITLE
Author as bot account?

### ISSUE THREAD

**Issue by max-sixty** [a-kenji/update-rust-toolchain#14]
Currently the author is set to me in https://github.com/prql/prql/pull/928. Is it possible to have it as a bot account, like `update-rust-toolchain`? 

This is the case for Dependabot and pre-commit.ci, though those are apps rather than workflows so might be different. It would also give this action lots of contributions, which could be good for getting the word out...

Thank you again!

**Comment by a-kenji** [comment]
Thanks for the question! Id be happy for any information about this issue in general.

> Is it possible to have it as a bot account, like `update-rust-toolchain`?

I am not sure, if this is possible as a GitHub Action. You can run it as the GitHub Action user itself, then native GitHub Action's wont be run on it. You can provide it with a token of a user that has `repo` access, then it will be run as the user, then GitHub Action's will be run on it.

I will look more into it!

**Comment by a-kenji** [comment]
The action is now run as the default github action bot user account. Sadly, it will still not trigger the CI to automatically run actions against the PR. 

For automatically running actions on the PR you would need to provide the action with a  PAT, or GithubToken.

**Comment by max-sixty** [comment]
Thanks @a-kenji !

We have this `pr-test-all` label (e.g. https://github.com/prql/prql/pull/926), which runs all the tests, so I can add that manually for the moment; hopefully GH will adjust their policies around being able to run the tests automatically at some point.
