### ISSUE TITLE
Getting an error in GHA

### ISSUE THREAD

**Issue by max-sixty** [a-kenji/update-rust-toolchain#16]
Hi there,

I recently changed our `minor-version-delta` from `2` to `1`.

Our cron job now breaks — https://github.com/prql/prql/runs/8292688495?check_suite_focus=true — is that something we're doing wrong?

The only change to the job was that character (https://github.com/prql/prql/pull/958/files), so I'm confused what might be going wrong.

Thank you v much again!

**Comment by a-kenji** [comment]
Hi @max-sixty,

Thank you for reaching out.
This was a bug on our side, you did nothing wrong!
I expect it to be fixed now, but would be happy if you could test it again and confirm it.

**Comment by max-sixty** [comment]
Thanks @a-kenji ! It runs every week so I'll post back if it fails next week.

**Comment by max-sixty** [comment]
Hi @a-kenji — is it pulling the correct version?

I'm still get an error (https://github.com/prql/prql/actions/runs/3044445552/jobs/4904842290)

But if I unpin the version, GHA complains: https://github.com/prql/prql/pull/963

Thanks!

**Comment by a-kenji** [comment]
@max-sixty,
I will release a version for the fixes fairly soon.
Does `a-kenji/update-rust-toolchain@main` work currently?

**Comment by max-sixty** [comment]
I'm actually getting a different error now; maybe `@main` isn't supported? https://github.com/prql/prql/actions/runs/3048152751/jobs/4912914296

**Comment by a-kenji** [comment]
This was a different error that surfaced now, I believe that I fixed it with #19.
So I expect it to work with `@main` now.
Thank you for all the patience and help with debugging!

**Comment by max-sixty** [comment]
Great — it works!
